name: "Golang Vulncheck"
description: "Performs vulnerability scan using govulncheck and afterwards uploads it as Sarif Report to Github"
author: "Templum"
inputs:
  package:
    description: "The package you want to scan, by default will be ./..."
    required: false
    default: "./..."
  github-token:
    description: "Github App token to upload sarif report. Needs write permissions for security_events. By default it will use 'github.token' value"
    default: ${{ github.token }}
    required: true

runs:
  using: "docker"
  image: "Dockerfile"
  env:
    GITHUB_TOKEN: "${{ inputs.github-token }}"

branding:
  icon: "alert-octagon"
  color: "red"
