name: "Rename"
description: "Rename"
author: "Templum"
inputs:
  packages:
    description: "Template."
    required: false
    default: "./..."
  version:
    description: "Version of govulncheck that should be used, by default it will be the latest"
    required: false
    default: "latest"

runs:
  using: "composite"
  steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
    - name: Get govulncheck
      run: go install golang.org/x/vuln/cmd/govulncheck@${{ inputs.version }}
      shell: bash
    - name: Create Share
      run: mkdir -p /tmp/
      shell: bash
    - name: Run govulncheck
      run: govulncheck -json ${{ inputs.packages }} > /tmp/vulncheck.json
      shell: bash
    - name: Build Action
      run: CGO_ENABLED=0 go build -ldflags="-w -s" -v -o action .
      shell: bash 
    - name: Interpret output
      run: ./action
      shell: bash
      

branding:
  icon: "alert-triangle"
  color: "red"
