name: "Golang Vulncheck"
description: "Performs vulnerability scan using govulncheck and afterwards uploads it as Sarif Report to Github"
author: "Templum"
inputs:
  package:
    description: "The package you want to scan, by default will be ./..."
    required: false
    default: "./..."
  version:
    description: "Version of govulncheck that should be used, by default it will be the latest"
    required: false
    default: "latest"
  github-token:
    description: Github App token to upload sarif report. Needs write permissions for security_events. By default it will use "github.token value". 
    default: ${{ github.token }}
    required: true

runs:
  using: "composite"
  steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
    - name: Install govulncheck binary
      run: go install golang.org/x/vuln/cmd/govulncheck@${{ inputs.version }}
      shell: bash
    - name: Build Action
      run: CGO_ENABLED=0 go build -ldflags="-w -s" -v -o action .
      shell: bash 
    - name: Perform Scan & Upload
      run: ./action
      shell: bash
      env:
        GITHUB_TOKEN: '${{ inputs.github-token }}'
      

branding:
  icon: "alert-octagon"
  color: "red"
