name: CI Flow
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # We must fetch at least the immediate parents so that if this is
          # a pull request then we can checkout the head.
          fetch-depth: 2
      # If this run was triggered by a pull request event, then checkout
      # the head of the pull request instead of the merge commit.
      - run: git checkout HEAD^2
        if: ${{ github.event_name == 'pull_request' }}
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.0
      - name: Compile Action
        run: go build -v ./...
  unit-testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # We must fetch at least the immediate parents so that if this is
          # a pull request then we can checkout the head.
          fetch-depth: 2
      # If this run was triggered by a pull request event, then checkout
      # the head of the pull request instead of the merge commit.
      - run: git checkout HEAD^2
        if: ${{ github.event_name == 'pull_request' }}
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.0
      - name: Run Unit Test with Racecondition Detector
        run: go test -race ./...
      - name: Run Unit Tests with Coverage
        run: go test -coverprofile=coverage.txt -covermode=atomic -v ./...
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          # token is not needed for public repositories
          files: coverage.txt
          flags: unit-tests
          name: codecov-action
          fail_ci_if_error: false