name: Integration Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Debug
        run: pwd && ls
        shell: bash
      - name: Integration Test
        id: integration-test
        uses: Templum/govulncheck-action@feature/2
        with:
          go-version: 1.18.3
