name: Integration Test
on:
  push:
    branches:
      - main
    tags:
      - v*
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Debug
        run: pwd && ls
        shell: bash
      - name: Integration Test
        id: integration-test
        uses: connectRN/govulncheck-action@main
