name: Integration Test
on: [push]
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Debug
        run: pwd && ls
        shell: bash
      - name: Main Integration Test
        uses: Templum/govulncheck-action@main
  dynamic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Debug
        run: pwd && ls
        shell: bash
      - name: Dynamic Integration Test
        uses: Templum/govulncheck-action@${{github.ref_name}}
