name: Integration Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Integration Test
        id: integration-test
        uses: Templum/govulncheck-action@main
        env:
          GITHUB_TOKEN: '${{secrets.GITHUB_TOKEN}}'
