name: Integration Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Integration Test
        id: integration-test
        uses: Templum/govulncheck-action@master
