name: Integration Test
on:
  push:
    branches:
      - main
      - feature/integration-test # Temporary for testing
    tags:
      - v*
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout playground repository
        uses: actions/checkout@main
        with:
          repository: Templum/playground
      - name: Run Action against known repository and skip upload to compare generated file
        uses: Templum/govulncheck-action@main
        with:
          skip-upload: true
          go-version: 1.19
        env:
          GH_PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
          GOPRIVATE: "github.com/Templum/private-lib"
      - name: Upload Report
        uses: actions/upload-artifact@v3
        with:
          name: raw-report
          path: raw-report.json